// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjas462V0stl0jomfJsWBr-Hiswm4lgE4',
    appId: '1:104867182863:web:763e93a5375aff6e2c267a',
    messagingSenderId: '104867182863',
    projectId: 'pab-remidi237',
    authDomain: 'pab-remidi237.firebaseapp.com',
    storageBucket: 'pab-remidi237.firebasestorage.app',
    measurementId: 'G-1JHZK9Q264',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVloW07Rs7hZawtbqeCPCnLuIwZHk1Djw',
    appId: '1:104867182863:android:4410961c2c677bec2c267a',
    messagingSenderId: '104867182863',
    projectId: 'pab-remidi237',
    storageBucket: 'pab-remidi237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFWhDrnHhBcOtdnP4MvICnu5nnm-zJNnA',
    appId: '1:104867182863:ios:c1286066589e59112c267a',
    messagingSenderId: '104867182863',
    projectId: 'pab-remidi237',
    storageBucket: 'pab-remidi237.firebasestorage.app',
    iosBundleId: 'com.example.remidi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFWhDrnHhBcOtdnP4MvICnu5nnm-zJNnA',
    appId: '1:104867182863:ios:c1286066589e59112c267a',
    messagingSenderId: '104867182863',
    projectId: 'pab-remidi237',
    storageBucket: 'pab-remidi237.firebasestorage.app',
    iosBundleId: 'com.example.remidi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjas462V0stl0jomfJsWBr-Hiswm4lgE4',
    appId: '1:104867182863:web:a683198a5215aeb32c267a',
    messagingSenderId: '104867182863',
    projectId: 'pab-remidi237',
    authDomain: 'pab-remidi237.firebaseapp.com',
    storageBucket: 'pab-remidi237.firebasestorage.app',
    measurementId: 'G-0LEFE3E0HX',
  );
}
